### PR TITLE
Add initial content for explanation/merges and syncs

### LINKED ISSUE #119: Write explanation "Importing changes from Debian (merges & syncs)"

### PR DESCRIPTION
**Pull request by dviererbe**
This PR adds the initial content for the explanation of syncs and merges from Debian unstable.

### CODE REVIEW

**Comment by dviererbe** [comment]
I looked through the CI errors:
- `synchronization` is marked as a spelling error. Most likely, because it wants it to be written as `synchronisation` 🙄 
- The refs `DebianImportFreeze`, `FeatureFreeze`, `FinalRelease`, etc. are not defined, because the follow up PR #54 does it. This also causes spell checking errors.
- Link check times out for `https://merges.ubuntu.com/*`. The long loading time for Merge-o-Matic is expected behavior. Maybe we should add a linkcheck ignore. Not ideal, but acceptable for me. We could also look into massively increasing the timeout time. Don't know what the value should be so that it is not flaky.
- The spelling checker also does not like the "Matic" of "Merge-o-Matic" and its acronym "MoM". This should be easily fixable.
- The `manpages.ubuntu.com` linkckecks are marked as 404 broken, but i can not figure out why. They work for me in a browser.

**Comment by s-makin** [comment]
>     * Link check times out for `https://merges.ubuntu.com/*`. The long loading time for Merge-o-Matic is expected behavior. Maybe we should add a linkcheck ignore. Not ideal, but acceptable for me. We could also look into massively increasing the timeout time. Don't know what the value should be so that it is not flaky.

I would agree with adding it to the linkcheck ignore. I think that would be better than increasing the timeout time, otherwise people working on PRs or making contributions will end up having frustrating experiences with the tests.

>     * The `manpages.ubuntu.com` linkckecks are marked as 404 broken, but i can not figure out why. They work for me in a browser.

I was having the same issue with manpages.ubuntu.com links in Pro docs. I couldn't see any legitimate reason for it, and the links were working when I clicked on them. I'd be a bit more hesitant about adding that to linkcheck ignore though, since there might be genuinely broken pages among those, which we will want to at least be prompted to check.

**Comment by dviererbe** [comment]
> I'd be a bit more hesitant about adding [manpages.ubuntu.com] to linkcheck ignore though, since there might be genuinely broken pages among those, which we will want to at least be prompted to check.

Fully agree, but I also do not know how to proceed here. Manually checking links every time can't be the solution :/

**Comment by dviererbe** [comment]
> > I'd be a bit more hesitant about adding [manpages.ubuntu.com] to linkcheck ignore though, since there might be genuinely broken pages among those, which we will want to at least be prompted to check.
> 
> Fully agree, but I also do not know how to proceed here. Manually checking links every time can't be the solution :/

suggestion: I could write a script that greps all :manpage:\`value\` and check it with curl and tell linkcheck to ignore manpage.ubuntu.com.

**Comment by dviererbe** [comment]
I through together this script. It even has the benefit of de-duplicating manpage checks.

```bash
#!/usr/bin/env bash

manpages=$(grep \
    --basic-regexp ':manpage:`.\+`' \
    --only-matching \
    --recursive --include '*.rst' docs \
    | cut --delimiter '`' --fields 2 \
    | sort --unique)
    
pass=true

for manpage in $manpages
do
    # assuming the pattern "PAGE(SECTION)"
    page="${manpage%%(*}"
    section="${manpage#*(}"
    section="${section%)*}"

    url="https://manpages.ubuntu.com/manpages/en/man${section}/${page}.${section}.html"

    if curl --silent --show-error $url > /dev/null
    then
        echo "INFO: Tested $manpage successfully (URL='$url')."
    else
        pass=false
        echo "ERROR: Failed to load manpage $manpage (URL='$url')."
    fi
done

if $pass
then
    echo "PASS: All manpages were accessible."
else
    echo "FAIL: One or more manpage(s) did not load properly."
    exit 1
fi

```

**Comment by dviererbe** [comment]
> I through together this script. It even has the benefit of de-duplicating manpage checks.
> 
> [...]

This does not work as intended, see: https://github.com/canonical/sphinx-docs-starter-pack/issues/224#issuecomment-2095356300, but I will incorporate a fix I suggested here: https://github.com/canonical/sphinx-docs-starter-pack/pull/236#issuecomment-2138041504

**Comment by dviererbe** [comment]
RTD fails with `ModuleNotFoundError: No module named 'distro_info'`, even though I added 

https://github.com/canonical/ubuntu-packaging-guide/blob/4db49e11ed3eb6ac06a9f5b699ef0005d57d36c3/.readthedocs.yaml#L16-L17

**Comment by dviererbe** [comment]
Adding 'distro_info' to custom_required_modules did the trick, but the GH actions fail with the same problem

**Comment by dviererbe** [comment]
Okay, what is going on here?

```
Status: install ok installed
Skip installing python3-distro-info, because it is already installed.
python3 build_requirements.py
Traceback (most recent call last):
  File "/home/runner/work/ubuntu-packaging-guide/ubuntu-packaging-guide/docs/build_requirements.py", line 4, in <module>
    from custom_conf import *
  File "/home/runner/work/ubuntu-packaging-guide/ubuntu-packaging-guide/docs/custom_conf.py", line 2, in <module>
    import distro_info
ModuleNotFoundError: No module named 'distro_info'
```

**Comment by dviererbe** [comment]
> Okay, what is going on here?
> 
> ```
> Status: install ok installed
> Skip installing python3-distro-info, because it is already installed.
> python3 build_requirements.py
> Traceback (most recent call last):
>   File "/home/runner/work/ubuntu-packaging-guide/ubuntu-packaging-guide/docs/build_requirements.py", line 4, in <module>
>     from custom_conf import *
>   File "/home/runner/work/ubuntu-packaging-guide/ubuntu-packaging-guide/docs/custom_conf.py", line 2, in <module>
>     import distro_info
> ModuleNotFoundError: No module named 'distro_info'
> ```

The venv config file `docs/.sphinx/venv/pyvenv.cfg` sets `include-system-site-packages = false`. To fix this we have to pass the `--system-site-packages` flag when setting up the venv

EDIT: Nope. Python still ignores the system package :/ I worked around this with 
https://github.com/canonical/ubuntu-packaging-guide/blob/6741acec4f10298ab2e49109a0a946470607e913/docs/custom_conf.py#L1-L2

**Comment by dviererbe** [comment]
rebased onto 2.0-preview to resolve merge conflict

**Comment by dviererbe** [comment]
YAY 🎉 All checks passed finally!

@rkratky If you review this we could get it merged :)

**Pull request merged**
