### PR TITLE
Update get-package-source.rst

### PR DESCRIPTION
**Pull request by waveform80**
Fix tiny inconsistency in "git-ubuntu"

### CODE REVIEW

**Comment by waveform80** [comment]
May be worth changing the references to "git-ubuntu", the project, to "git ubuntu", or possibly going the other way and always using "git-ubuntu" instead?

**Comment by s-makin** [comment]
> May be worth changing the references to "git-ubuntu", the project, to "git ubuntu", or possibly going the other way and always using "git-ubuntu" instead?

I would recommend using "git-ubuntu" everywhere. In all the docs I've seen so far "git-ubuntu" seems to be how it's written. Ofc this doesn't mean it can't or won't change between now and the git-ubuntu docs actually being released publicly, but the advantage is that it makes it clear that this is an actual thing and not a sub-command of git.

**Comment by waveform80** [comment]
> but the advantage is that it makes it clear that this is an actual thing and not a sub-command of git.

Technically, once installed, it is a sub-command of git, but I do agree it's probably better to just be consistent throughout and use `git-ubuntu`; I'll push a change to the branch in a mo

**Comment by dviererbe** [comment]
I agree, we should use `git-ubuntu` to be consistent. Thanks for opening the PR!

**Comment by dviererbe** [comment]
Thought: maybe we should add an automated check for `git ubuntu` without the `-`

**Pull request merged**
