### PR TITLE
migarte to sphinx tabs

### LINKED ISSUE #130: Use Canonical sphinx documentation pack – 2.0 Release (meta-issue)
This issue serves as a tracker for all issues and pull requests related to setting up and maintaining the use of the [Canonical Sphinx documentation pack](https://github.com/canonical/sphinx-docs-starter-pack) for the Ubuntu Packaging Guide as part of the 2.0 release (see #19).

### Motivation

- Ensure consistency with other Ubuntu/Canonical documentation.
- Modernize and improve the existing documentation.

### Scope

This issue covers tasks such as:

- Updating dependencies and configurations.
- Refining styles and templates for consistency.
- Addressing structural improvements and best practices.
- Resolving any related bugs or enhancement requests.

Feel free to link relevant issues and PRs here for better tracking.

### PR DESCRIPTION
**Pull request by dviererbe**
- adds the `sphinx_tabs.tabs` extension
- migrates all `sphinx_design` tabs to `sphinx_tabs` tabs

Todo: PR #49 needs to be merged first, as this PR is based on it. 

Note: Until PR #49 is merged this PR will show the branch `FR-6485-sync-with-canonical-sphinx-docs-starter-pack` as it's merge target. This is just to better see the diff. 

Note: Additional context: #30

### CODE REVIEW

**Comment by dviererbe** [comment]
@rkratky sorry if I accidentally spammed your email inbox. I misunderstood the GitHub UI and accidentally added/removed you as a reviewer.

**Comment by dviererbe** [comment]
Note: rebased onto changed FR-6485-sync-with-canonical-sphinx-docs-starter-pack (context: https://github.com/canonical/ubuntu-packaging-guide/pull/49#issuecomment-1918856317)

**Review by rkratky — APPROVED** [review]
LGTM, thank you!

**Comment by rkratky** [comment]
> @rkratky sorry if I accidentally spammed your email inbox. I misunderstood the GitHub UI and accidentally added/removed you as a reviewer.

No problem at all :)

**Pull request merged**
