### PR TITLE
Add files needed for readthedocs setup

### LINKED ISSUE #3: Setup Read the Docs
The `main` branch should automatically be deployed to Read the Docs.

This issue tracks this effort.

### PR DESCRIPTION
**Pull request by s-makin**
Add doc/ folder with:
  - all rst pages
  - images
  - up-to-date logo
  - Sphinx required elements
  - Preliminary Diataxis structure

### CODE REVIEW

**Review by dviererbe — APPROVED** [review]
**Praise:** Thanks for porting this! Just seeing the packaging guide in the newer design is so much nicer.

**Issue(if-minor):** The images do not get displayed when I run `make run` (Note: If you want to fix this in a separate PR then consider this issue non-blocking).
I could make it work by moving them into the `_static` folder and rename the image locations in the pages files e.g. `.. image:: ../images/cycle-items.png` -> `.. image:: ../_static/images/png/cycle-items.png`.  

**Question(non-blocking):** Is it possible to integrate translations into this theme? If yes, how do we replace the old bazaar workflow?

**Question(non-blocking):** Is it possible to integrate an edit button that redirects to the source file of the page?

**Thought:** I think we can just throw away the `.png` files when we have the `.svg` source files. They are usually smaller and scale better.

**Nitpick:** Can we rename `circle_of_friends.png` just to `ubuntu_logo.png` or similar?

**Note:** How to build the docs locally should be documented in the future. Part of our targeting audience have little or no experience with `make` and have problems resolving dependency issues.

**Comment by dviererbe** [comment]
Note: the current images have a weird contrast in Dark Mode
image

**Comment by s-makin** [comment]
> Note: the current images have a weird contrast in Dark Mode image

Pretty much all the images need a bit of an overhaul to make them more palatable, with better contrast and choice of font etc. I think we should aim to use something code-based like Mermaids wherever we can, to make it easier to update images in the future - plain images like these have a much higher burden of maintenance in the long run.

The furo theme does allow for light and dark mode versions of images though, we have that for the logo in the cloud-init docs. We just need to create them.

**Comment by s-makin** [comment]
> **Praise:** Thanks for porting this! Just seeing the packaging guide in the newer design is so much nicer.

:D thanks for the feedback, you made some excellent points. I propose that although I *could* address some of the issues now, since none are strictly blocking and none prevent the RTD setup, that we should merge this PR as-is. After I've set up the RTD project, I can address your feedback in the follow-up Diataxis PR. The advantage to that being that once RTD is set up we will have PR previews in RTD, which is much easier and more convenient than local building. 

> **Issue(if-minor):** The images do not get displayed when I run `make run` (Note: If you want to fix this in a separate PR then consider this issue non-blocking). I could make it work by moving them into the `_static` folder and rename the image locations in the pages files e.g. `.. image:: ../images/cycle-items.png` -> `.. image:: ../_static/images/png/cycle-items.png`.

Yeah, I expected it to be a little wonky lol. I didn't update any of the pages to point to the new image locations, since I knew I was going to do a Diataxis reshuffle right after and all the pages would be in different folders anyway. The next PR will be the Diataxis one, which should solve that problem.

> **Question(non-blocking):** Is it possible to integrate translations into this theme? If yes, how do we replace the old bazaar workflow?

Yes we can, but the how depends on which localisation extension we end up using (I think). I vaguely remember promising to look into that, but it doesn't affect the RTD setup so I'll do it after the Diataxis PR.
 
> **Question(non-blocking):** Is it possible to integrate an edit button that redirects to the source file of the page?

Yes, RTD includes that by default - although the feedback button at the top hijacks that default "edit on GitHub" link, so it might need a bit of wizardry to get both. We can look into it, although I'd rather add that to the to-do list for now and we can chat about how we want that functionality to work in one of the catchups :) 
 
> **Thought:** I think we can just throw away the `.png` files when we have the `.svg` source files. They are usually smaller and scale better.

Agreed, svg is always better than png. I didn't actually look at the images though to see if any of the content was changed. If it's just design improvements then I'll delete the png versions in the next PR. 

> **Nitpick:** Can we rename `circle_of_friends.png` just to `ubuntu_logo.png` or similar?

I don't see why not :)
 
> **Note:** How to build the docs locally should be documented in the future. Part of our targeting audience have little or no experience with `make` and have problems resolving dependency issues.

Good idea. I'll probably add it to my to-do list for now, since the docs will (presumably) be private while we're working on them.

**Comment by dviererbe** [comment]
Ref: #3

**Pull request merged**
